version: 2.1

jobs:
  build-docker-image:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      - run:
          name: "Build Docker Image"
          command: |
            IMAGE_NAME=ghcr.io/${GITHUB_USERNAME}/${GITHUB_REPO}
            docker build -t ${IMAGE_NAME}:${CIRCLE_SHA1} .
            docker tag ${IMAGE_NAME}:${CIRCLE_SHA1} ${IMAGE_NAME}:latest
      - run:
          name: "Login to GitHub Container Registry"
          command: echo "$GITHUB_TOKEN" | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
      - run:
          name: "Push Docker Image to GHCR"
          command: |
            IMAGE_NAME=ghcr.io/${GITHUB_USERNAME}/${GITHUB_REPO}
            docker push ${IMAGE_NAME}:${CIRCLE_SHA1}
            docker push ${IMAGE_NAME}:latest
            
workflows:
  # Build and push Docker image on every commit
  build-workflow:
    jobs:
      - build-docker-image

  # Scheduled workflow that runs daily
  daily-build:
    triggers:
      - schedule:
          # Run at 9:00 AM UTC every day
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build-docker-image
