name: Multi-Arch Docker Build

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-architectures:
    strategy:
      matrix:
        include:
          - platform: "linux/amd64"
            machine: ubuntu-latest
            arch_suffix: amd64
          - platform: "linux/arm64"
            machine: ubuntu-24.04-arm
            arch_suffix: arm64

    name: Build dfw (${{ matrix.arch_suffix }})
    runs-on: ${{ matrix.machine }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase image name
        id: lowercase
        run: |
          echo "image=ghcr.io/${{ github.repository_owner }}/dfw" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT

      - name: Pull existing image for cache
        continue-on-error: true
        run: |
          docker pull ${{ steps.lowercase.outputs.image }}:${{ matrix.arch_suffix }} || true

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.lowercase.outputs.image }}:${{ matrix.arch_suffix }}
          platforms: ${{ matrix.platform }}
          cache-to: type=gha,mode=max
          cache-from: |
            type=gha

  create-multiarch-manifest:
    needs: build-architectures
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase image name
        id: lowercase
        run: |
          echo "image=ghcr.io/${{ github.repository_owner }}/dfw" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT

      - name: Create and push multi-arch manifest
        run: |
          SOURCE_IMAGES=(
            "${{ steps.lowercase.outputs.image }}:amd64"
            "${{ steps.lowercase.outputs.image }}:arm64"
          )
          
          echo "Creating manifest for latest tag"
          docker buildx imagetools create -t "${{ steps.lowercase.outputs.image }}:latest" "${SOURCE_IMAGES[@]}"

      - name: Inspect multi-arch image
        run: |
          docker buildx imagetools inspect ${{ steps.lowercase.outputs.image }}:latest
